{% set name = "UPV" %}
{% set version = "3.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://git.ligo.org/virgo/virgoapp/{{ name }}/-/archive/{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: d6fb19e30498196fd2c187d2ba92eb613586f954d415ce9f71e4a20cbf23bfbf
  patches:
    # use rootcling from build env when cross-compiling
    - rootcling-cross.patch  # [build_platform != target_platform]

build:
  error_overdepending: true
  error_overlinking: true
  number: 5
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - cmake >=3.12.0
    - make  # [unix]
    - pkg-config  # [unix]
    - root_base  # [build_platform != target_platform]
  host:
    - vetoperf >=3.2.0
    - omicron >=4.0.0
    - gwollum >=4.0.0
    - root_base
  run:
    - vetoperf >=3.2.0
    - omicron >=4.0.0
    - gwollum >=4.0.0
    - root_base

test:
  requires:
    - pkg-config
  commands:
    # sanity check
    - upv version
    # check pkg-config
    - pkg-config --print-errors --exact-version {{ version }} {{ name|lower }}

about:
  home: https://virgo.docs.ligo.org/virgoapp/{{ name }}/
  doc_url: https://virgo.docs.ligo.org/virgoapp/{{ name }}/
  dev_url: https://git.ligo.org/virgo/virgoapp/{{ name }}.git
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: UPV is a software analysis tool designed to measure noise correlations for gravitational-wave detectors and to produce optimal time-domain vetoes.

extra:
  recipe-maintainers:
    - duncanmmacleod
    - rhyspoulton
